[project]
name = "poc-registration-service"
version = "0.1.0"
description = "Python fastapi example"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi",
]

[dependency-groups]
dev = [
    "workers-py"
]